# 主项目的 config.yaml
email_attacher:
  poll_interval: 60
  attachment_save_path: "./attachments"
  processed_emails_path: "./processed_emails.json"
  providers:
    - type: "qq"
      config:
        imap_addr: "imap.qq.com"
        port: 993
        username: "1733889704@qq.com"
        password: "rzdcdscowjbmbaeg"
  retry_config:
    max_attempts: 3
    interval: "10s"

cv_helper:
  mongo_uri: "mongodb://192.168.1.58:27017"
  database: "easyhr"
  username: "root"
  password: "123456"
  collection: "cvs"