# 主项目的 config.yaml
email_attacher:
  poll_interval: 60
  attachment_save_path: "./attachments"
  processed_emails_path: "./processed_emails.json"
  providers:
    - type: "qq"
      config:
        imap_addr: "imap.qq.com"
        port: 993
        smtp_addr: "smtp.qq.com"
        smtp_port: 587
        username: "1733889704@qq.com"
        password: "rzdcdscowjbmbaeg"
  retry_config:
    max_attempts: 3
    interval: "10s"

cv_helper:
  mongo_uri: "mongodb://192.168.1.58:27017"
  database: "easyhr"
  username: "root"
  password: "123456"
  collection: "cvs"

# SMTP配置，用于发送邮件回复
smtp_config:
  smtp_server: "smtp.qq.com"
  smtp_port: 587
  username: "1733889704@qq.com"
  password: "rzdcdscowjbmbaeg"
  use_tls: true
  from_email: "1733889704@qq.com"
  from_name: "easyHR招聘组"

agents:
  promptDir: "easyHR/internal/agent/prompts"
  providers:
    - role: "primary"
      model_type: "gemini3"
      api_key: "AIzaSyC7858OJh5rfJ5hy5x3YZfP0uM0bRGUz9c"
      base_url: "https://api.openai.com/v1"
      session_id: "primary_session"
      model_name: "gemini-2.5-flash"
    - role: "secondary"
      model_type: "gemini3"
      api_key: "AIzaSyC7858OJh5rfJ5hy5x3YZfP0uM0bRGUz9c"
      base_url: "https://api.openai.com/v1"
      session_id: "secondary_session"
      model_name: "gemini-2.5-flash"

rabbitmq:
  host: "14.103.175.18"
  port: 5672
  username: "admin"
  password: "admin123"
